### ISSUE TITLE
Get the status of a SQL statement execution completion

### ISSUE THREAD

**Issue by baozaolaoba-top** [nixpulvis/bevy_sqlx#21]
How can I tell when a SQL statement has finished executing? When requesting to execute SQL, the event_id is not obtained synchronously. If there are 3 SQL statements (A, B, and C) to be executed, and I want to do something after B is executed, how can I handle it? Or how can I get the event_id corresponding to B?

**Comment by nixpulvis** [comment]
Perhaps I'm misunderstanding. Are the `SqlxEventStatus` events not enough? They include the event's ID, as well. Or is the issue that you don't get that ID when you create the event? I could see that being something we're missing at the moment.
